AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Strapi-test
Resources:
  strapi-sf:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: sam-app/src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 100
      CodeUri: .
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
          Name:
            Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
          ResourceQuery:
            Type: CLOUDFORMATION_STACK_1_0
      ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
          ResourceGroupName:
            Ref: ApplicationResourceGroup
          AutoConfigurationEnabled: 'true'
